<a href="https://colab.research.google.com/github/FabioASC/DNC-Case/blob/main/regrassao_logistica_Aula.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import seaborn as sns

In [3]:
dataset = sns.load_dataset("iris")
dataset.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
x = dataset.iloc[:,:-1]
y = dataset.iloc[:,-1]

In [5]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [6]:
model = LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [7]:
predict = model.predict(x_test)

In [9]:
x_test["prediction"] = predict
y_test = pd.DataFrame(y_test)

x_test["Real"] = y_test["species"]

x_test.head(20)

,sepal_length,sepal_width,petal_length,petal_width,prediction,Real
135,7.7,3.0,6.1,2.3,virginica,virginica
50,7.0,3.2,4.7,1.4,versicolor,versicolor
70,5.9,3.2,4.8,1.8,virginica,versicolor
42,4.4,3.2,1.3,0.2,setosa,setosa
119,6.0,2.2,5.0,1.5,versicolor,virginica
26,5.0,3.4,1.6,0.4,setosa,setosa
54,6.5,2.8,4.6,1.5,versicolor,versicolor
45,4.8,3.0,1.4,0.3,setosa,setosa
128,6.4,2.8,5.6,2.1,virginica,virginica
73,6.1,2.8,4.7,1.2,versicolor,versicolor
15,5.7,4.4,1.5,0.4,setosa,setosa
137,6.4,3.1,5.5,1.8,virginica,virginica
92,5.8,2.6,4.0,1.2,versicolor,versicolor
97,6.2,2.9,4.3,1.3,versicolor,versicolor
47,4.6,3.2,1.4,0.2,setosa,setosa
56,6.3,3.3,4.7,1.6,versicolor,versicolor
61,5.9,3.0,4.2,1.5,versicolor,versicolor
11,4.8,3.4,1.6,0.2,setosa,setosa
27,5.2,3.5,1.5,0.2,setosa,setosa
122,7.7,2.8,6.7,2.0,virginica,virginica