<a href="https://colab.research.google.com/github/FabioASC/DNC-Case/blob/main/RegressaoLogistica_golf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder

In [5]:
arquivo = r'/content/drive/MyDrive/Colab Notebooks/Dados/golf_df.xlsx'
df_golf = pd.read_excel(arquivo)
df_golf.head()

      clima  temp umidade vento jogar
0     sunny   hot    high    no    no
1     sunny   hot    high   yes    no
2  overcast   hot    high    no   yes
3     rainy  mild    high    no   yes
4     rainy  cool  normal    no   yes

In [14]:
# Tranformar
le = LabelEncoder()

le.fit(df_golf.clima)
df_golf.clima = le.transform(df_golf.clima)

le.fit(df_golf.temp)
df_golf.temp = le.transform(df_golf.temp)

le.fit(df_golf.umidade)
df_golf.umidade = le.transform(df_golf.umidade)

le.fit(df_golf.vento)
df_golf.vento = le.transform(df_golf.vento)

le.fit(df_golf.jogar)
df_golf.jogar = le.transform(df_golf.jogar)

df_golf.head()

   clima  temp  umidade  vento  jogar
0      2     1        0      0      0
1      2     1        0      1      0
2      0     1        0      0      1
3      1     2        0      0      1
4      1     0        1      0      1

In [18]:
x = df_golf.iloc[:,:-1]
y = df_golf[["jogar"]]

In [19]:
model = LogisticRegression()
model.fit(x,y)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [20]:
predict = model.predict(x)

In [22]:
x["Predicao"] = predict

y = pd.DataFrame(y)

x["Real"] = y["jogar"]

x.head(20)

    clima  temp  umidade  vento  Predicao  Real
0       2     1        0      0         0     0
1       2     1        0      1         0     0
2       0     1        0      0         1     1
3       1     2        0      0         1     1
4       1     0        1      0         1     1
5       1     0        1      1         1     0
6       0     0        1      1         1     1
7       2     2        0      0         0     0
8       2     0        1      0         1     1
9       1     2        1      0         1     1
10      2     2        1      1         1     1
11      0     2        0      1         1     1
12      0     1        1      0         1     1
13      1     2        0      1         1     0